### ISSUE TITLE
Ignore multiple characters in ignoreNextTo

### ISSUE THREAD

**Issue by wickedest** [Trott/remark-lint-prohibited-strings#174]
We want to ensure that when Docker is written, it is "Docker".  But we also have cases where we reference a command, e.g. a really contrived example with 4 textual instances of the word:
```
Wow, Docker is great, see [docker run](https://docker.com). Check your /docker folder, or run "docker".
```

Naively, an attempt to ignore "docker run": `{ yes: 'Docker', ignoreNextTo: 'run' }` won't work because the negative lookahead is an immediate character before _or_ after the text (it might be useful to clarify this in the doc):
```
(?<!\.|@[a-zA-Z0-9/-]*)\b(?<!run)(Docker)(?!run)\b(?!\.\w)
```

Naively, an attempt to compensate might include a regex whitespace to ignore `{ yes: 'Docker', ignoreNextTo: '\s+run' }` , but that doesn't work because the string is escaped.  Only an actual space `' run'` will work, but that now creates a rule where the negative look behind is checking "runDocker", which is fine, but a little inefficient and not exactly what I wanted.  But the same rule cannot be reused for the `/` and `"` characters.  The `ignoreNextTo` works best with single characters.

Creating multiple rules just generates multiple issues because the _same_ text is processed each time for each rule.  A rather silly example is "adocker dockerb".  "a" can be ignored in one rule and "b" in another, but the first rule will complain about "dockerb" and the second will complain about "adocker".

The problem I see here is that the rule needs to be powerful enough to handle **all** possible cases in a single rule, and it's not, and technical text can contain a lot of quotes and slashes.

One idea might be to allow `ignoreNextTo` to be an array, e.g.:
```
ignoreNextTo: [ '"', '\'', '/', '\s+run' ]
```

It's not perfect because it's making the regex _more_ complex (and it's already very complex), and the negative lookbehind is still weird checking for "\s+rundocker".  In this array case, would allow the text to be regex.  It doesn't have to, but it's strange having to write `' run'` and it gives more flexibility.

I'd be happy to make PR for this.

**Comment by Trott** [comment]
I'm doing some clean-up and this one seems dormant. If there's an intention to implement this, leave a comment or re-open.  Thanks!
