### ISSUE TITLE
Documentation needs some clarification

### ISSUE THREAD

**Issue by wickedest** [Trott/remark-lint-prohibited-strings#175]
After spending a lot of time with the code and reading the doc, there are some clarifications that need to be made to the docs.

1. clearly state that `no` is optional (the text suggests `no` can be "omitted").
2. `yes` is required.  this should be clear, and should appear before `no` for this reason.
3. `no` states that "if no is omitted but yes is supplied".  this suggests that `yes` is optional.  I'd suggest delete this bit "~~but yes is supplied~~".  Also, if `yes` is used in this manner, `yes` is interpreted as a string literal (not regex).  Add an example of this.
4. `ignoreNextTo` is interpreted as a literal sequence of character(s) that appear _immediately before or after_ the `yes` pattern. It does not support regex.

**Comment by Trott** [comment]
Fixed in e516303
