### ISSUE TITLE
new line

### ISSUE THREAD

**Issue by muescha** [Trott/remark-lint-prohibited-strings#42]
with current version the search not include the newline character

it match the position over many lines

```shell
$ remark docs/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/ --report vfile-reporter
docs/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/index.md
   2:1-5:16  warning  Use "Gatsby" instead of "Gatsby.js"  prohibited-strings  remark-lint
  5:92-7:56  warning  Use "Gatsby" instead of "Gatsby.js"  prohibited-strings  remark-lint
```

```markdown
---
title: Moving from create-react-app to Gatsby.js
date: 2018-06-18
author: Khaled Garbaya
canonicalLink: https://khaledgarbaya.net/articles/moving-from-create-react-app-to-gatsby-js
publishedAt: Khaled Garbaya Blog
excerpt: How to Move from create-react-app to Gatsby.js
tags: [contentful, react]
---
```

```json
{
  "plugins": [
    [
      "remark-lint-prohibited-strings",
      [
        {
          "no": "[Gg]atsby[.]?[Jj][Ss]",
          "yes": "Gatsby"
        }
      ]
    ]
  ]
}
```

**Comment by muescha** [comment]
note: the line 5 is only 91 chars long, but the resulting start column is 92

**Comment by Trott** [comment]
> with current version the search not include the newline character

This is intentional. This allows for prohibited phrases, not just words, since phrases can be split across multiple lines.

That said, I can see how this might be surprising and may be worth making configurable.

> note: the line 5 is only 91 chars long, but the resulting start column is 92

The column numbers come from remark-lint, so if there's a bug there, it's in that or a dependency.

**Comment by muescha** [comment]
some how i expected only 2:40-2:48
the starting is also here 2:1 
🤔 

so the best is to make an issue at remark-lint?

**Comment by Trott** [comment]
> so the best is to make an issue at remark-lint?

Not sure to be honest. There might be a way to determine more precisely where the lint error is and maybe we're just not using that functionality. Will take a look when I get some time, but surely won't mind if someone else beats me to it....

**Comment by muescha** [comment]
i see much more wrong positions with the gatsby site

as a first glimpse i see in this line a missing `position` parameter:

https://github.com/Trott/remark-lint-prohibited-strings/blob/cb09671932fddb1315d04174df99049f3a777a91/index.js#L43


```javascript
        /**
         * Associates a message with the file for `reason` at `position`.
         * When an error is passed in as `reason`, copies the stack.
         * Each message has a `fatal` property which by default is set to `false` (ie. `warning`).
         * @param reason Reason for message. Uses the stack and message of the error if given.
         * @param position Place at which the message occurred in `vfile`.
         * @param ruleId Category of message.
         */
        message: (reason: string, position?: Unist.Point | Unist.Position | Unist.Node, ruleId?: string) => vfileMessage.VFileMessage;
```


something like this:

https://github.com/remarkjs/remark-lint/blob/873212e55c591332f9251eccbb0ceb96a2e8cbda/packages/remark-lint-checkbox-content-indent/index.js#L78-L81

**Comment by Trott** [comment]
> i think the lint should give back an exact position of the match like in this lint package

@muescha Thanks for gathering and presenting all the information! If you want to open a pull request, please do! Otherwise, I'll probably get to this some time over the weekend.

**Comment by muescha** [comment]
i try to dig into it.

**Comment by Trott** [comment]
Sorry, didn't see your comment until a short while ago. I think I've got this solved, but feel free to submit a PR anyway or review mine.... And thanks for all the great feature requests, bug reports, and comments.

**Comment by muescha** [comment]
my solution is similar, but not ready to PR - https://github.com/muescha/remark-lint-prohibited-strings/commit/0f76ed93dea76a6460aa42aba3717b8b50c9dda9

added also multiple results and some debug info for a reporter

`message.id` i used to filter off the messages depending on the search string

**Comment by Trott** [comment]
> my solution is similar, but not ready to PR - [muescha@0f76ed9](https://github.com/muescha/remark-lint-prohibited-strings/commit/0f76ed93dea76a6460aa42aba3717b8b50c9dda9)
> 
> added also multiple results and some debug info for a reporter
> 
> `message.id` i used to filter off the messages depending on the search string

Multiple results especially should be incorporated. I made a mental note of it and then promptly forgot, so yeah, that would be great!
