### ISSUE TITLE
@-mention matching should be case-insensitive

### ISSUE THREAD

**Issue by Trott** [Trott/remark-lint-prohibited-strings#44]
> btw: `[a-z0-9/-]` why is there no `A-Z` here?

I think that's a bug. It probably was intended to be case-insensitive. That part of the reg exp makes sure that we skip checking things that are part of an @-mention. So, even though Nodejs prohibits `v8` as a string, it permits it in `@nodejs/v8`. This bug means that the skipping won't work for `@Nodejs./v8` which would be a bug.

_Originally posted by @Trott in https://github.com/Trott/remark-lint-prohibited-strings/issues/43#issuecomment-619320058_

**Comment by muescha** [comment]
i think this can be reverted with #41 case insensitive

**Comment by Trott** [comment]
We'll want to keep the test that was added, but yes, the code in `index.js` can be reverted.
